#!/usr/bin/env python

"""check_minecraft: A plugin for Nagios3 or Icinga2 for monitoring the
status of as Minecraft server."""

__author__      = "Mark Rogaski"
__email__       = "mrogaski@pobox.com"
__copyright__   = "Copyright 2015, Mark Rogaski"
__license__     = "MIT"
__version__     = "0.1.0"

import argparse
import nagiosplugin
import logging

_log = logging.getLogger('nagiosplugin')

class MCServer(nagiosplugin.Resource):
    def __init__(self, address, port=25565):
        self.address = address
        self.port = port
        self.version = None

    def probe(self):
        _log.debug('using dummy data')
        return [nagiosplugin.Metric('online', True, context='status'),
                nagiosplugin.Metric('players', 10, min=0, max=64,
                                    context='slots')]


def main():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('address', metavar='ADDRESS',
                      help='hostname or IP address of the server')
    argp.add_argument('-v', '--verbose', action='count', default=0)
    argp.add_argument('-p', '--port', metavar='PORT', default=25565,
                      help='TCP port number of the server')
    args = argp.parse_args()
    check = nagiosplugin.Check(
        MCServer(args.address, args.port),
        nagiosplugin.Context('status'),
        nagiosplugin.ScalarContext('slots'))
    check.main(args.verbose)

if __name__ == '__main__':
    main()

